# _____             _                 _____ _____ 
#|   __|___ ___ ___| |_ ___ _ _ _____|     |   __|
#|__   | . | -_|  _|  _|  _| | |     |  |  |__   |
#|_____|  _|___|___|_| |_| |___|_|_|_|_____|_____|
#      |_|   
# SpectrumOS - Embrace the Chromatic Symphony!
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#                           |___|           |___|    
# SpectrumOS - Configuration File

PYWAL_BACKEND="wal"
PYWAL_LIGHT_SCHEME="Dark"
GOWALL_SCHEME="No Theme"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
TRANSITION_DURATION="3"
CURRENT_WALLPAPER="/var/lib/spectrumos/current.png"
