# _____             _                 _____ _____ 
#|   __|___ ___ ___| |_ ___ _ _ _____|     |   __|
#|__   | . | -_|  _|  _|  _| | |     |  |  |__   |
#|_____|  _|___|___|_| |_| |___|_|_|_|_____|_____|
#      |_|   
# SpectrumOS - Embrace the Chromatic Symphony!
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence
# SpectrumOS Hyprland Configuration
# Decoration

decoration {
    rounding = 2    

    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }

    shadow {
        enabled = no
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}
