# SpectrumOS hyprlock configuration
# Now using pywal colors.css

source = $HOME/.cache/wal/colors-hyprland.conf

# BACKGROUND
background {
    monitor =
    path = /var/lib/spectrumos/current.png
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

image {
    monitor =
    path = $HOME/SpectrumOS.png
    size = 300
    rounding = 0
    border_size = 0
    position = 0, 250
    halign = center
    valign = center
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 
    dots_spacing = 0.35 
    dots_center = true
    outer_color = $color1
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $foreground
    fade_on_empty = false
    rounding = -1
    check_color = $color3
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $foreground
    font_size = 22
    font_family = JetBrains Mono
    position = 0, 500
    halign = center
    valign = center
}

# TIME
label {
    monitor = 
    text = cmd[update:1000] echo "$(date +"%-I:%M")"
    color = $foreground
    font_size = 95
    font_family = Fira Code Medium
    position = 0, 600
    halign = center
    valign = center
}

# Profile Picture
image {
    monitor =
    path = $HOME/.face
    size = 100
    border_size = 2
    border_color = $foreground
    position = 0, -100
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(playerctl metadata --format '{{title}} - {{artist}}' || echo 'No media playing')" 
    color = $foreground
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $USER
    color = $foreground
    font_size = 14
    font_family = JetBrains Mono
    position = 0, -10
    halign = center
    valign = top
}
