# Cursor
cursor_shape beam
cursor_blink_interval 3

# Allow remote control
allow_remote_control yes

# Middle-click copy
mouse_map button2 press copy_to_clipboard

# Include Pywal colors
include ~/.cache/wal/colors-kitty.conf

# Fonts
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12.0

# Appearance
background_opacity 0.95
window_padding_width 8
enable_audio_bell no

# Performance
repaint_delay 6
input_delay 1
sync_to_monitor yes

# Scrolling
scrollback_lines 5000
scrollback_pager less --chop-long-lines

# Clipboard behavior
copy_on_select yes
paste_from_clipboard yes
confirm_os_window_close 0
